name: Test-Package
on: [push, release]
jobs:
  TestInstallUnix:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Test-requirements
        run: python3 test.py -y
      - name: Test-Install-requirements
        run: python3 test.py

      - name: Remove-requirements
        run: rm -rf pipinstaller/resources/requirements.txt
      - name: Test
        run: python3 test.py -y
      - name: Test-Install
        run: python3 test.py
  
  TestInstallWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Test-requirements
        run: py -3 test.py -y
      - name: Test-Install-requirements
        run: py -3 test.py

      - name: Remove-requirements
        run: del /f pipinstaller/resources/requirements.txt
      - name: Test
        run: py -3 test.py -y
      - name: Test-Install
        run: py -3 test.py