name: Verify-Release
on: release
jobs:
  TestInstallUnix:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Test
        run: "python3 install.py -y"
      - name: Test-Install
        run: "python3 install.py"
  
  TestInstallWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Test
        run: "py -3 install.py -y"
      - name: Test-Install
        run: "py -3 install.py"